services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file: ".env"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s

  server:
    container_name: nerkhin-server
    image: ${DOCKER_HUB_USERNAME}/${IMAGE_TAG}
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    restart: unless-stopped
    volumes:
      - server-data:/data
    depends_on:
      postgres:
        condition: service_healthy
    env_file: ".env"

volumes:
  postgres-data:
  server-data:
