CREATE TABLE IF NOT EXISTS professor (
    id                  BIGINT          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name           VARCHAR(50)     NOT NULL,
    email               VARCHAR(100)    NOT NULL UNIQUE,
    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);