CREATE TABLE IF NOT EXISTS grade (
    id                  BIGINT          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_id          BIGINT          NOT NULL REFERENCES student (id) ON DELETE CASCADE,
    course_id           BIGINT          NOT NULL REFERENCES course (id) ON DELETE CASCADE,
    grade               DECIMAL         NOT NULL,
    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(student_id, course_id)
);
