CREATE TABLE IF NOT EXISTS course (
    id              BIGINT          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(50)     NOT NULL,
    credits         INTEGER         NOT NULL,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);